GET http://localhost:9000/api/v1/organizations
Accept: application/json

###

DELETE http://localhost:9000/api/v1/organizations/7
Accept: application/json

###
POST http://localhost:9000/api/v1/organizations
Accept: application/json
Content-Type: application/json

{
  "name": "name",
  "address": "address",
  "ogrn": "ogrn",
  "inn": "inn",
  "okvd": "okvd",
  "supportForm": {
    "name": "name",
    "target": "target",
    "period": "period",
    "size": "size"
  },
  "violationInformation": "violation"
}
